"""
HTML report builder.

Generates a standalone ``report.html`` page with embedded CSS for
easy sharing and viewing in any browser.
"""

from pathlib import Path
from typing import Any, Dict, List

from recon.logger import get_logger
from recon.modules.probe import LiveHost
from recon.pipeline.manager import ScanStatistics

log = get_logger()

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Reconnaissance Report — {domain}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; padding: 2rem; }}
  .container {{ max-width: 1200px; margin: 0 auto; }}
  h1 {{ color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: 0.5rem; margin-bottom: 1.5rem; }}
  h2 {{ color: #f0883e; margin-top: 2rem; margin-bottom: 0.75rem; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; }}
  th, td {{ text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #21262d; }}
  th {{ background: #161b22; color: #8b949e; font-weight: 600; }}
  tr:hover {{ background: #1c2128; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 2rem; font-size: 0.75rem; font-weight: 600; }}
  .badge-green {{ background: #1b4727; color: #3fb950; }}
  .badge-red {{ background: #491c1c; color: #f85149; }}
  .badge-yellow {{ background: #4d3a1a; color: #d29922; }}
  .badge-gray {{ background: #21262d; color: #8b949e; }}
  pre {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; overflow-x: auto; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 0.85rem; margin-bottom: 1rem; }}
  code {{ font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; }}
  .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }}
  .stat-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; text-align: center; }}
  .stat-card .value {{ font-size: 2rem; font-weight: 700; color: #58a6ff; }}
  .stat-card .label {{ font-size: 0.8rem; color: #8b949e; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; font-size: 0.8rem; color: #8b949e; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <h1>🔍 Reconnaissance Report</h1>
  <p><strong>Domain:</strong> <code>{domain}</code> &nbsp;|&nbsp;
     <strong>Duration:</strong> <code>{duration}</code></p>

  <h2>📊 Summary</h2>
  <div class="stats-grid">
    <div class="stat-card"><div class="value">{subdomain_count}</div><div class="label">Subdomains</div></div>
    <div class="stat-card"><div class="value">{live_count}</div><div class="label">Live Hosts</div></div>
    <div class="stat-card"><div class="value">{screenshot_count}</div><div class="label">Screenshots</div></div>
    <div class="stat-card"><div class="value">{port_count}</div><div class="label">Ports Scanned</div></div>
    <div class="stat-card"><div class="value">{nuclei_count}</div><div class="label">Nuclei Findings</div></div>
  </div>

  <h2>⏱️ Execution Statistics</h2>
  <table>
    <thead><tr><th>Stage</th><th>Status</th><th>Duration</th></tr></thead>
    <tbody>
      {stage_rows}
    </tbody>
  </table>

  <h2>🌐 Subdomains</h2>
  {subdomains_section}

  <h2>🟢 Live Hosts</h2>
  {live_hosts_section}

  <h2>🔧 Technology Detection</h2>
  {technology_section}

  <h2>🔌 Port Scan (Nmap)</h2>
  {port_scan_section}

  <h2>⚠️ Vulnerability Scan (Nuclei)</h2>
  {nuclei_section}

  <div class="footer">
    Generated by <a href="https://github.com/NASHEDIxCODER/recon" style="color: #58a6ff;">Recon</a>
    — Advanced Reconnaissance Framework
  </div>
</div>
</body>
</html>
"""


def _format_duration(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"


def _status_badge(status_name: str) -> str:
    badges = {
        "COMPLETED": "badge badge-green",
        "SKIPPED": "badge badge-yellow",
        "FAILED": "badge badge-red",
        "PENDING": "badge badge-gray",
        "RUNNING": "badge badge-yellow",
    }
    cls = badges.get(status_name, "badge badge-gray")
    return f'<span class="{cls}">{status_name}</span>'


def build_html_report(
    data_store: Dict[str, Any],
    stats: ScanStatistics,
    output_path: Path,
) -> None:
    """Generate a standalone HTML report from the pipeline data store.

    Parameters
    ----------
    data_store:
        Shared pipeline data store containing scan results.
    stats:
        Aggregated scan statistics.
    output_path:
        Destination file path for the HTML report.
    """
    subdomains: List[str] = data_store.get("subdomains", [])
    live_hosts: List[LiveHost] = data_store.get("live_hosts", [])
    technologies: List[str] = data_store.get("technologies", [])
    port_scan_results: List[str] = data_store.get("port_scan_results", [])
    nuclei_findings: List[str] = data_store.get("nuclei_findings", [])

    # Stage rows
    stage_rows = ""
    for stage in stats.stage_results:
        stage_rows += (
            f"<tr><td>{stage.stage_name}</td>"
            f"<td>{_status_badge(stage.status.name)}</td>"
            f"<td>{_format_duration(stage.duration_seconds)}</td></tr>\n"
        )

    # Subdomains
    if subdomains:
        subdomains_section = "<pre>" + "\n".join(subdomains) + "</pre>"
    else:
        subdomains_section = "<p><em>No subdomains discovered.</em></p>"

    # Live hosts
    if live_hosts:
        rows = ""
        for host in live_hosts:
            tech_str = ", ".join(host.technologies) if host.technologies else "-"
            rows += (
                f"<tr><td>{host.url}</td><td>{host.status_code}</td>"
                f"<td>{host.title}</td><td>{tech_str}</td></tr>\n"
            )
        live_hosts_section = (
            "<table><thead><tr><th>URL</th><th>Status</th><th>Title</th>"
            "<th>Technologies</th></tr></thead><tbody>\n"
            f"{rows}</tbody></table>"
        )
    else:
        live_hosts_section = "<p><em>No live hosts found.</em></p>"

    # Technologies
    if technologies:
        tech_list = "".join(f"<li>{t}</li>\n" for t in technologies)
        technology_section = f"<ul>{tech_list}</ul>"
    else:
        technology_section = "<p><em>No technologies detected.</em></p>"

    # Port scan
    if port_scan_results:
        port_scan_section = "<pre>" + "\n".join(port_scan_results) + "</pre>"
    else:
        port_scan_section = "<p><em>Port scan not performed or no results.</em></p>"

    # Nuclei
    if nuclei_findings:
        nuclei_section = "<pre>" + "\n".join(nuclei_findings) + "</pre>"
    else:
        nuclei_section = "<p><em>No vulnerabilities found or scan not performed.</em></p>"

    html = _HTML_TEMPLATE.format(
        domain=data_store.get("domain", "Unknown"),
        duration=_format_duration(stats.duration_seconds),
        subdomain_count=len(subdomains),
        live_count=len(live_hosts),
        screenshot_count=stats.screenshots_taken,
        port_count=stats.ports_scanned,
        nuclei_count=stats.nuclei_findings,
        stage_rows=stage_rows,
        subdomains_section=subdomains_section,
        live_hosts_section=live_hosts_section,
        technology_section=technology_section,
        port_scan_section=port_scan_section,
        nuclei_section=nuclei_section,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    log.debug("HTML report written to %s", output_path)